parameters:
    majpanel.entity_namespace: 'App\Entity'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Majpanel\MajpanelBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/MajpanelBundle.php'

    Majpanel\MajpanelBundle\Service\AdminGenerator:
        arguments:
            $entityNamespace: '%majpanel.entity_namespace%'
